using System.IO;
using System.Text.Json;
using Hatrack;

internal static class Tests
{
    private static int passed;
    private static void Check(string name,Action action){action();Console.WriteLine("PASS "+name);passed++;}
    private static void Assert(bool value,string message="Assertion failed"){if(!value)throw new Exception(message);}
    private static void Throws(Action action){try{action();}catch{return;}throw new Exception("Expected failure");}
    [STAThread]static int Main(){var root=Path.Combine(Path.GetTempPath(),"Hatrack-tests-"+Guid.NewGuid().ToString("N"));Environment.SetEnvironmentVariable("HATRACK_TEST_HOME",root);try{
        Check("Unicode name and reserved-path validation",()=>{Assert(Paths.ValidateName("仕事 Purple")=="仕事 Purple");foreach(var s in new[]{"","../bad","CON","A\nB","bad."})Throws(()=>Paths.ValidateName(s));});
        Check("Untested vendor versions need one confirmation per version",()=>{var c=new Catalog();Assert(!Compatibility.NeedsConfirmation(new(DesktopApp.Claude,"unused","2.19675.0.0","test"),c));Assert(!Compatibility.NeedsConfirmation(new(DesktopApp.Codex,"unused","26.930.2377.0","test"),c));var newer=new Installation(DesktopApp.Codex,"unused","99.0.0.0","test");Assert(Compatibility.NeedsConfirmation(newer,c));c.AcceptedVersions[DesktopApp.Codex]="99.0.0.0";Assert(!Compatibility.NeedsConfirmation(newer,c));Assert(Compatibility.NeedsConfirmation(newer with {Version="99.1.0.0"},c));Assert(Compatibility.Warning(newer).Contains("99.0.0.0"));});
        Check("Pre-rename catalogue folder keeps being used until Hatrack has its own",()=>{var local=Path.Combine(root,"local");Directory.CreateDirectory(Path.Combine(local,"Profiles"));Assert(Paths.DataRoot(local)==Path.Combine(local,"Hatrack"));File.WriteAllText(Path.Combine(local,"Profiles","catalog.json"),"{}");Assert(Paths.DataRoot(local)==Path.Combine(local,"Profiles"));Directory.CreateDirectory(Path.Combine(local,"Hatrack"));File.WriteAllText(Path.Combine(local,"Hatrack","catalog.json"),"{}");Assert(Paths.DataRoot(local)==Path.Combine(local,"Hatrack"));});
        Check("Invalid and oversized images rejected",()=>{Directory.CreateDirectory(root);var f=Path.Combine(root,"bad.png");File.WriteAllText(f,"not a PNG");Throws(()=>Icons.Load(f));Throws(()=>Icons.Render("notacolor","Windows","P"));Throws(()=>Icons.Render("#ffffff","Windows","P",zoom:double.NaN));});
        Check("Vendor marks preserve transparency and shape when recoloured",()=>{foreach(var shape in new[]{"Claude logo","Codex logo"}){var yellow=Icons.Render("#EAB308",shape,"P");var purple=Icons.Render("#7C3AED",shape,"P");var a=new byte[256*256*4];var b=new byte[a.Length];yellow.CopyPixels(a,1024,0);purple.CopyPixels(b,1024,0);var filled=0;for(var i=0;i<a.Length;i+=4){Assert(a[i+3]==b[i+3]);if(a[i+3]==255){filled++;Assert(a[i]==8&&a[i+1]==179&&a[i+2]==234);}}Assert(filled>1000&&filled<45000);Assert(a[3]==0);}});
        Check("Custom dark controls and popup items inherit readable foregrounds",()=>{var window=new System.Windows.Window();AppTheme.Attach(window);AppTheme.Apply(window,"Dark");var ink=(System.Windows.Media.SolidColorBrush)window.FindResource("Ink");var surface=(System.Windows.Media.SolidColorBrush)window.FindResource("Surface");Assert(ink.Color.R>240&&surface.Color.R<40);var item=new System.Windows.Controls.ComboBoxItem{Content="Dark item"};var combo=new System.Windows.Controls.ComboBox();combo.Items.Add(item);window.Content=combo;combo.ApplyTemplate();item.ApplyTemplate();Assert(((System.Windows.Media.SolidColorBrush)combo.Foreground).Color==ink.Color);Assert(((System.Windows.Media.SolidColorBrush)item.Foreground).Color==ink.Color);Assert(combo.Template.FindName("PART_Popup",combo)!=null);AppTheme.Apply(window,"Light");Assert(((System.Windows.Media.SolidColorBrush)combo.Foreground).Color.R<30);window.Close();});
        Profile first=null!;
        Check("Transactional profile creation and matching shortcuts",()=>{first=ProfileService.Save(null,DesktopApp.Claude,"Test Ω",new("Windows","#7C3AED",""),true,true);Assert(Directory.Exists(first.DataPath));Assert(Shell.Owns(first.DesktopPath,first.Id));Assert(Shell.Owns(first.StartMenuPath,first.Id));Assert(File.Exists(first.IconPath));var bytes=File.ReadAllBytes(first.IconPath);Assert(BitConverter.ToUInt16(bytes,4)==7);});
        Check("Duplicate names fail without adding catalogue entries",()=>{Throws(()=>ProfileService.Save(null,DesktopApp.Claude,"test Ω",new("Windows","#7C3AED",""),false,false));Assert(CatalogStore.Read().Profiles.Count==1);});
        Check("Unknown shortcut is never overwritten; creation rolls back",()=>{var link=Path.Combine(Paths.Desktop,"Collision (Claude).lnk");File.WriteAllText(link,"sentinel");var before=Directory.GetDirectories(Path.Combine(root,"profiles")).Length;Throws(()=>ProfileService.Save(null,DesktopApp.Claude,"Collision",new("Windows","#7C3AED",""),true,false));Assert(File.ReadAllText(link)=="sentinel");Assert(CatalogStore.Read().Profiles.Count==1);Assert(Directory.GetDirectories(Path.Combine(root,"profiles")).Length==before);});
        Check("Rename preserves identity, data, and removes only old owned shortcut",()=>{File.WriteAllText(Path.Combine(first.DataPath,"sentinel"),"keep");var renamed=ProfileService.Save(first.Id,DesktopApp.Claude,"Renamed",new("Diamond","#EAB308",""),true,true);Assert(renamed.Id==first.Id&&renamed.AppId==first.AppId&&renamed.DataPath==first.DataPath);Assert(!File.Exists(first.DesktopPath));Assert(Shell.Owns(renamed.DesktopPath,first.Id));first=renamed;});
        Check("Claude launch paths with spaces are individual arguments",()=>{var spec=Launcher.LaunchSpec(first,new(DesktopApp.Claude,"C:\\App Path\\Claude.exe","test","test"));Assert(!spec.UseShellExecute&&spec.ArgumentList.Count==2);Assert(spec.ArgumentList[0]=="--user-data-dir="+first.DataPath);});
        Check("Locked metadata commit rolls back new shortcuts and directories",()=>{var before=Directory.GetDirectories(Path.Combine(root,"profiles")).Length;using(var locked=new FileStream(Paths.Catalog+".bak",FileMode.Open,FileAccess.Read,FileShare.None)){Throws(()=>ProfileService.Save(null,DesktopApp.Claude,"Locked Commit",new("Windows","#0F766E",""),true,true));}Assert(CatalogStore.Read().Profiles.Count==1);Assert(!File.Exists(Path.Combine(Paths.Desktop,"Locked Commit (Claude).lnk")));Assert(!File.Exists(Path.Combine(Paths.Start,"Locked Commit (Claude).lnk")));Assert(Directory.GetDirectories(Path.Combine(root,"profiles")).Length==before);});
        Profile codex=null!;
        Check("Codex desktop state and file credentials separated",()=>{codex=ProfileService.Save(null,DesktopApp.Codex,"Codex Work",new("Folder","#2563EB",""),false,false);Environment.SetEnvironmentVariable("OPENAI_API_KEY","test-sentinel");Environment.SetEnvironmentVariable("CODEX_SQLITE_HOME","unrelated");var spec=Launcher.LaunchSpec(codex,new(DesktopApp.Codex,"C:\\App\\ChatGPT.exe","test","test"));Assert(spec.Environment["CODEX_HOME"]==codex.DataPath);Assert(Paths.Inside(spec.Environment["CODEX_ELECTRON_USER_DATA_PATH"]!,Paths.ProfileRoot(codex.Id)));Assert(!spec.Environment.ContainsKey("OPENAI_API_KEY")&&!spec.Environment.ContainsKey("CODEX_SQLITE_HOME"));Assert(File.ReadAllText(Path.Combine(codex.DataPath,"config.toml")).Contains("\"file\""));Environment.SetEnvironmentVariable("OPENAI_API_KEY",null);Environment.SetEnvironmentVariable("CODEX_SQLITE_HOME",null);});
        Check("Codex keyring configuration fails closed",()=>{File.WriteAllText(Path.Combine(codex.DataPath,"config.toml"),"cli_auth_credentials_store = \"keyring\"\n");Throws(()=>Launcher.LaunchSpec(codex,new(DesktopApp.Codex,"C:\\App\\ChatGPT.exe","test","test")));});
        Check("Pre-rename shortcuts stay owned and are repaired to Hatrack",()=>{var legacy=Path.Combine(Path.GetDirectoryName(Paths.OwnExe)!,"Profiles.exe");Shell.Shortcut(first.DesktopPath,first,legacy);Assert(Shell.Owns(first.DesktopPath,first.Id));Assert(ProfileService.RepairShortcuts()==1);Assert(Paths.Same(Shell.ReadShortcut(first.DesktopPath).Target,Paths.OwnExe));Assert(ProfileService.RepairShortcuts()==0);});
        Check("Removing launcher preserves profile data",()=>{ProfileService.Remove(first.Id);Assert(!File.Exists(first.DesktopPath));Assert(File.ReadAllText(Path.Combine(first.DataPath,"sentinel"))=="keep");Assert(CatalogStore.Read().Profiles.Count==1);});
        Check("Concurrent catalogue updates do not lose entries",()=>{Parallel.For(0,10,i=>CatalogStore.Update(c=>{c.Locations[(DesktopApp)(100+i)]="sentinel-"+i;return true;}));Assert(CatalogStore.Read().Locations.Count==10);});
        Check("Corrupt catalogue fails closed, preserving backup",()=>{var backup=File.ReadAllBytes(Paths.Catalog+".bak");File.WriteAllText(Paths.Catalog,"{bad");Throws(()=>CatalogStore.Read());Assert(File.ReadAllBytes(Paths.Catalog+".bak").SequenceEqual(backup));});
        Console.WriteLine($"{passed} checks passed. Desktop login isolation still requires manual acceptance.");return 0;
    }catch(Exception e){Console.Error.WriteLine(e);return 1;}finally{Environment.SetEnvironmentVariable("HATRACK_TEST_HOME",null);if(Directory.Exists(root)&&Path.GetFileName(root).StartsWith("Hatrack-tests-"))Directory.Delete(root,true);}}
}
