using System.IO;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;

namespace Hatrack;
public sealed class EditorWindow : Window
{
    private readonly List<Installation> installs;private readonly Profile? existing;private readonly DiscoveredProfile? imported;
    private readonly ComboBox app=new(){ItemsSource=Enum.GetValues<DesktopApp>(),SelectedIndex=0,MinHeight=40};
    private readonly TextBox name=new(){MinHeight=40},color=new(){Text="#D97757",MinHeight=40};
    private readonly ComboBox shape=new(){ItemsSource=Icons.Shapes,SelectedIndex=0,MinHeight=40};
    private readonly ComboBox background=new(){ItemsSource=new[]{"Transparent","#FFFFFF","#171717"},SelectedIndex=0,MinHeight=40};
    private readonly CheckBox desktop=new(){Content="Desktop shortcut",IsChecked=true},start=new(){Content="Start Menu shortcut",IsChecked=true},favorite=new(){Content="Favourite",IsChecked=false};
    private readonly StackPanel dependencyActions=new(){Orientation=Orientation.Horizontal,Margin=new Thickness(0,8,0,12)};
    private readonly Slider zoom=new(){Minimum=.5,Maximum=4,Value=1},x=new(){Minimum=-1,Maximum=1,Value=0},y=new(){Minimum=-1,Maximum=1,Value=0};
    private readonly Image preview=new(){Width=160,Height=160},small=new(){Width=32,Height=32},smallDark=new(){Width=32,Height=32};
    private readonly TextBlock error=new(){Foreground=new SolidColorBrush(Color.FromRgb(174,39,39)),TextWrapping=TextWrapping.Wrap},dependency=new(){TextWrapping=TextWrapping.Wrap};
    private string upload="",manualExe="";private bool initialized;
    private readonly Button save=new(){Content="Create profile",Padding=new Thickness(22,11,22,11)};
    public EditorWindow(List<Installation> installations,Profile? profile=null,DiscoveredProfile? candidate=null)
    {
        installs=installations;existing=profile;imported=candidate;Title=profile!=null?"Edit profile":"Create a desktop profile";Width=840;Height=780;MinWidth=760;MinHeight=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;FontFamily=new FontFamily("Segoe UI");FontSize=14;
        AppTheme.Attach(this);save.Style=(Style)FindResource("PrimaryButton");error.SetResourceReference(TextBlock.ForegroundProperty,"Error");
        var root=new DockPanel();var frame=new Border{Padding=new Thickness(28),Child=root};frame.SetResourceReference(Border.BackgroundProperty,"Canvas");Content=frame;
        var title=new StackPanel{Margin=new Thickness(0,0,0,20)};title.Children.Add(new TextBlock{Text=Title,FontSize=26,FontWeight=FontWeights.SemiBold});title.Children.Add(new TextBlock{Text="Desktop apps only. Your sign-in happens inside the official app.",Margin=new Thickness(0,8,0,0)});DockPanel.SetDock(title,Dock.Top);root.Children.Add(title);
        var bottom=new StackPanel{Margin=new Thickness(0,14,0,0)};bottom.Children.Add(error);var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0,12,0,0)};var cancel=new Button{Content="Cancel",Padding=new Thickness(18,11,18,11),Margin=new Thickness(0,0,12,0)};cancel.Click+=(_,_)=>Close();actions.Children.Add(cancel);actions.Children.Add(save);bottom.Children.Add(actions);DockPanel.SetDock(bottom,Dock.Bottom);root.Children.Add(bottom);
        var grid=new Grid();grid.ColumnDefinitions.Add(new ColumnDefinition());grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(240)});root.Children.Add(grid);
        var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};var fields=new StackPanel{Margin=new Thickness(0,0,26,0)};scroll.Content=fields;grid.Children.Add(scroll);
        Add(fields,"Desktop app",app);fields.Children.Add(dependency);var locate=new Button{Content="Locate app",Padding=new Thickness(12,7,12,7)};var download=new Button{Content="Official download",Padding=new Thickness(12,7,12,7),Margin=new Thickness(10,0,0,0)};dependencyActions.Children.Add(locate);dependencyActions.Children.Add(download);fields.Children.Add(dependencyActions);
        Add(fields,"Profile name",name);Add(fields,"Icon design",shape);
        var swatches=new WrapPanel{Margin=new Thickness(0,0,0,10)};foreach(var hex in Icons.Presets){var button=new Button{Width=32,Height=32,MinHeight=32,Padding=new Thickness(0),Margin=new Thickness(0,0,8,6),Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex)),ToolTip=hex};System.Windows.Automation.AutomationProperties.SetName(button,"Choose colour "+hex);button.Click+=(_,_)=>color.Text=hex;swatches.Children.Add(button);}fields.Children.Add(swatches);
        var colorRow=new DockPanel();var chooseColor=new Button{Content="Pick colour",Padding=new Thickness(12,6,12,6),Margin=new Thickness(10,0,0,0)};DockPanel.SetDock(chooseColor,Dock.Right);colorRow.Children.Add(chooseColor);colorRow.Children.Add(color);Add(fields,"Icon colour (hex)",colorRow);System.Windows.Automation.AutomationProperties.SetName(color,"Icon colour (hex)");
        var uploadRow=new StackPanel{Orientation=Orientation.Horizontal};var chooseImage=new Button{Content="Upload PNG, JPEG or ICO",Padding=new Thickness(12,8,12,8)};var reset=new Button{Content="Use design",Padding=new Thickness(12,8,12,8),Margin=new Thickness(10,0,0,0)};uploadRow.Children.Add(chooseImage);uploadRow.Children.Add(reset);fields.Children.Add(uploadRow);
        var advanced=new StackPanel();Add(advanced,"Image size / padding",zoom);Add(advanced,"Crop horizontal",x);Add(advanced,"Crop vertical",y);Add(advanced,"Icon background",background);fields.Children.Add(new Expander{Header="Size, crop and background",Content=advanced,Margin=new Thickness(0,14,0,6)});
        var shortcuts=new WrapPanel{Margin=new Thickness(0,8,0,0)};foreach(var cb in new[]{desktop,start,favorite}){cb.Margin=new Thickness(0,0,16,6);shortcuts.Children.Add(cb);}fields.Children.Add(shortcuts);
        if(profile!=null){var tools=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,22,0,0)};var folder=new Button{Content="Open data folder",Padding=new Thickness(10,8,10,8)};folder.Click+=(_,_)=>Process.Start(new ProcessStartInfo("explorer.exe"){Arguments="\""+profile.DataPath+"\"",UseShellExecute=true});var remove=new Button{Content="Remove launcher",Padding=new Thickness(10,8,10,8),Margin=new Thickness(12,0,0,0)};remove.Click+=(_,_)=>{if(System.Windows.MessageBox.Show(this,"Remove Hatrack shortcuts and its library entry? Your login, history, and profile folders will be preserved.","Remove launcher",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;try{ProfileService.Remove(profile.Id);DialogResult=true;}catch(Exception ex){error.Text=ex.Message;}};tools.Children.Add(folder);tools.Children.Add(remove);fields.Children.Add(tools);}
        if(candidate!=null)fields.Children.Add(new TextBlock{Text="Importing existing data:\n"+candidate.DataPath+"\nOriginal shortcuts will be preserved.",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,16,0,0)});
        var right=new StackPanel{Margin=new Thickness(8,0,0,0)};Grid.SetColumn(right,1);grid.Children.Add(right);right.Children.Add(new TextBlock{Text="Your icon",FontSize=18,FontWeight=FontWeights.SemiBold});var surface=new Border{Background=Brushes.White,CornerRadius=new CornerRadius(14),Padding=new Thickness(20),Margin=new Thickness(0,18,0,18),Child=preview};right.Children.Add(surface);right.Children.Add(new TextBlock{Text="Taskbar size",Margin=new Thickness(0,0,0,12)});var sizes=new StackPanel{Orientation=Orientation.Horizontal};sizes.Children.Add(new Border{Background=new SolidColorBrush(Color.FromRgb(243,243,245)),CornerRadius=new CornerRadius(11),Padding=new Thickness(16),Child=small,Margin=new Thickness(0,0,12,0)});sizes.Children.Add(new Border{Background=new SolidColorBrush(Color.FromRgb(37,37,40)),CornerRadius=new CornerRadius(11),Padding=new Thickness(16),Child=smallDark});right.Children.Add(sizes);right.Children.Add(new TextBlock{Text="One icon across your desktop, Start Menu, and profile window.\n\nUpdates to running windows apply after reopening the profile.\n\nNo account credentials are copied.",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,24,0,0),Foreground=(Brush)FindResource("Muted")});
        app.SelectionChanged+=(_,_)=>{if(existing==null&&shape.SelectedItem is string s&&s is "Claude logo" or "Codex logo"){shape.SelectedItem=(DesktopApp)app.SelectedItem==DesktopApp.Claude?"Claude logo":"Codex logo";color.Text=(DesktopApp)app.SelectedItem==DesktopApp.Claude?"#D97757":"#7C3AED";}UpdateDependency();};name.TextChanged+=(_,_)=>Preview();color.TextChanged+=(_,_)=>Preview();shape.SelectionChanged+=(_,_)=>Preview();background.SelectionChanged+=(_,_)=>Preview();zoom.ValueChanged+=(_,_)=>Preview();x.ValueChanged+=(_,_)=>Preview();y.ValueChanged+=(_,_)=>Preview();
        chooseImage.Click+=(_,_)=>{var dialog=new Microsoft.Win32.OpenFileDialog{Filter="Icon images|*.png;*.jpg;*.jpeg;*.ico",Title="Upload your own icon"};if(dialog.ShowDialog(this)!=true)return;try{Icons.Load(dialog.FileName);upload=dialog.FileName;zoom.Value=1;x.Value=y.Value=0;Preview();}catch(Exception ex){error.Text=ex.Message;}};
        reset.Click+=(_,_)=>{upload="";Preview();};
        chooseColor.Click+=(_,_)=>{var picker=new ColourPickerWindow(this,color.Text);if(picker.ShowDialog()==true)color.Text=picker.SelectedColour;};
        locate.Click+=(_,_)=>{var dialog=new Microsoft.Win32.OpenFileDialog{Filter="Desktop app (*.exe)|*.exe",Title="Locate official desktop executable"};if(dialog.ShowDialog(this)!=true)return;try{var install=Discovery.Validate((DesktopApp)app.SelectedItem,dialog.FileName);manualExe=install.Executable;installs.RemoveAll(i=>i.App==install.App);installs.Add(install);CatalogStore.Update(c=>{c.Locations[install.App]=install.Executable;return true;});UpdateDependency();}catch(Exception ex){error.Text=ex.Message;}};
        download.Click+=(_,_)=>Process.Start(new ProcessStartInfo(Discovery.DownloadUrls[(DesktopApp)app.SelectedItem]){UseShellExecute=true});
        save.Click+=(_,_)=>Save();
        if(profile!=null){app.SelectedItem=profile.App;app.IsEnabled=false;name.Text=profile.Name;color.Text=profile.Color;if(profile.Shape!="Upload"&&!Icons.Shapes.Contains(profile.Shape))shape.ItemsSource=Icons.Shapes.Append(profile.Shape).ToArray();shape.SelectedItem=profile.Shape=="Upload"?(profile.App==DesktopApp.Claude?"Claude logo":"Codex logo"):profile.Shape;if(profile.Shape=="Upload")upload=profile.IconSource;desktop.IsChecked=profile.DesktopPath!="";start.IsChecked=profile.StartMenuPath!="";favorite.IsChecked=profile.Favorite;manualExe=profile.ExecutableOverride;save.Content="Save profile";}
        else if(candidate!=null){app.SelectedItem=candidate.App;app.IsEnabled=false;name.Text=candidate.Name+" Imported";}
        else name.Text="Personal";
        initialized=true;Preview();UpdateDependency();
        Loaded+=(_,_)=>{AppTheme.Attach(this,Owner);foreach(var text in right.Children.OfType<TextBlock>())text.SetResourceReference(TextBlock.ForegroundProperty,"Muted");};
        var detector=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromSeconds(4)};detector.Tick+=async(_,_)=>{if(installs.Any(i=>i.App==(DesktopApp)app.SelectedItem))return;try{var found=await Task.Run(()=>Discovery.Detect(CatalogStore.Read()));installs.Clear();installs.AddRange(found);UpdateDependency();}catch{}};Loaded+=(_,_)=>detector.Start();Closed+=(_,_)=>detector.Stop();
    }
    private static void Add(StackPanel panel,string label,UIElement control){panel.Children.Add(new TextBlock{Text=label,Margin=new Thickness(0,12,0,7),FontWeight=FontWeights.SemiBold});panel.Children.Add(control);if(control is Control c)System.Windows.Automation.AutomationProperties.SetName(c,label);}
    private void Preview(){if(!initialized)return;try{var image=Icons.Render(color.Text,(string)shape.SelectedItem,name.Text,upload,zoom.Value,x.Value,y.Value,(string)background.SelectedItem);preview.Source=image;small.Source=smallDark.Source=image;error.Text="";}catch(Exception e){error.Text=e.Message;}}
    private void UpdateDependency(){if(!initialized)return;var selected=(DesktopApp)app.SelectedItem;var found=installs.FirstOrDefault(i=>i.App==selected);dependency.Text=found==null?selected+" Desktop not found. Locate it or download it below.":selected+" Desktop detected · "+found.Version;dependencyActions.Visibility=found==null?Visibility.Visible:Visibility.Collapsed;save.IsEnabled=found!=null;}
    private void Save(){try{var selected=(DesktopApp)app.SelectedItem;if(!installs.Any(i=>i.App==selected))throw new InvalidOperationException("Install or locate the official desktop app first.");ProfileService.Save(existing?.Id,selected,name.Text,new((string)shape.SelectedItem,color.Text,upload,zoom.Value,x.Value,y.Value,(string)background.SelectedItem),desktop.IsChecked==true,start.IsChecked==true,imported?.DataPath,manualExe,favorite.IsChecked==true);DialogResult=true;}catch(Exception e){error.Text=e.Message;}}
}
