using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;

namespace Hatrack;
public partial class MainWindow : Window
{
    private Catalog catalog=new();private List<Installation> installations=new();private bool favorites,ready,refreshing;private DateTime detected;
    private readonly System.Windows.Threading.DispatcherTimer timer=new(){Interval=TimeSpan.FromSeconds(5)};
    public MainWindow(){InitializeComponent();VersionText.Text=Program.Version+" · Preview";Loaded+=async(_,_)=>{try{catalog=CatalogStore.Read();Theme.SelectedIndex=catalog.Theme=="Dark"?2:catalog.Theme=="Light"?1:0;ApplyTheme(catalog.Theme);ready=true;await Refresh();timer.Tick+=async(_,_)=>await Refresh(false);timer.Start();}catch(Exception e){Error(e);}};Closed+=(_,_)=>timer.Stop();}
    private async Task Refresh(bool verbose=true){if(refreshing)return;refreshing=true;try{catalog=CatalogStore.Read();
        // Package detection starts PowerShell; background ticks only re-detect when an app is still missing.
        if(verbose||installations.Count<Enum.GetValues<DesktopApp>().Length&&DateTime.UtcNow-detected>TimeSpan.FromSeconds(30)){installations=await Task.Run(()=>Discovery.Detect(catalog));detected=DateTime.UtcNow;}
        InstallStatus.Text=string.Join("     ",Enum.GetValues<DesktopApp>().Select(a=>installations.FirstOrDefault(i=>i.App==a)is{}i?$"{a} Desktop detected · {i.Version}":$"{a} Desktop not found · use Locate desktop app"));Render();if(verbose)Status.Text="Existing profiles are only changed when you explicitly import or edit them.";}catch(Exception e){if(verbose)Error(e);}finally{refreshing=false;}}
    private void Render(){if(!ready)return;var query=Search.Text.Trim();var filter=AppFilter.SelectedIndex;var list=catalog.Profiles.Where(p=>(!favorites||p.Favorite)&&(filter==0||(int)p.App==filter-1)&&(query==""||p.Name.Contains(query,StringComparison.OrdinalIgnoreCase))).OrderByDescending(p=>p.Favorite).ThenBy(p=>p.Name).Select(p=>new{p.Id,p.Name,p.IconSource,Detail=$"{p.App} Desktop · {(p.Imported?"Imported":"Separate local data")}{(IsRunning(p.Id)?" · Running":"")}{(p.Favorite?" · Favourite":"")}"}).ToList();ProfileList.ItemsSource=list;EmptyState.Visibility=list.Count==0?Visibility.Visible:Visibility.Collapsed;EmptyTitle.Text=catalog.Profiles.Count==0?"Create your first profile.":"No matching profiles.";EmptyCopy.Text=catalog.Profiles.Count==0?"Create your first profile, or find the ones you already use. Existing logins and shortcuts stay where they are.":"Try a different search or filter, or create a profile.";}
    private static bool IsRunning(Guid id){try{using var m=Mutex.OpenExisting("Local\\Profiles.Launch."+id.ToString("N"));return true;}catch(WaitHandleCannotBeOpenedException){return false;}}
    private void All_Click(object sender,RoutedEventArgs e){favorites=false;AllNav.Tag="Selected";FavoritesNav.Tag=null;Render();}
    private void Favorites_Click(object sender,RoutedEventArgs e){favorites=true;AllNav.Tag=null;FavoritesNav.Tag="Selected";Render();}
    private void Filter_Changed(object sender,RoutedEventArgs e)=>Render();
    private async void Create_Click(object sender,RoutedEventArgs e){var window=new EditorWindow(installations){Owner=this};if(window.ShowDialog()==true)await Refresh();}
    private async void Edit_Click(object sender,RoutedEventArgs e){try{var id=(Guid)((Button)sender).Tag;var p=catalog.Profiles.Single(p=>p.Id==id);var window=new EditorWindow(installations,p){Owner=this};if(window.ShowDialog()==true)await Refresh();}catch(Exception ex){Error(ex);}}
    private void Open_Click(object sender,RoutedEventArgs e){try{Launcher.Start((Guid)((Button)sender).Tag);Status.Text="Opening a separate desktop profile…";}catch(Exception ex){Error(ex);}}
    private async void Locate_Click(object sender,RoutedEventArgs e){var choice=ChooseApp();if(choice==null)return;var dialog=new Microsoft.Win32.OpenFileDialog{Title=$"Locate {choice} Desktop executable",Filter="Desktop application (*.exe)|*.exe"};if(dialog.ShowDialog(this)!=true)return;try{var found=Discovery.Validate(choice.Value,dialog.FileName);CatalogStore.Update(c=>{c.Locations[choice.Value]=found.Executable;return true;});await Refresh();}catch(Exception ex){Error(ex);}}
    private DesktopApp? ChooseApp(){var dialog=new Window{Owner=this,Title="Choose desktop app",Width=420,Height=190,ResizeMode=ResizeMode.NoResize,WindowStartupLocation=WindowStartupLocation.CenterOwner};var panel=new StackPanel{Margin=new Thickness(24)};panel.Children.Add(new TextBlock{Text="Which desktop app would you like to locate?",Margin=new Thickness(0,0,0,20)});var row=new StackPanel{Orientation=Orientation.Horizontal};DesktopApp? result=null;foreach(var app in Enum.GetValues<DesktopApp>()){var button=new Button{Content=app+" Desktop",Margin=new Thickness(0,0,12,0),Padding=new Thickness(14,8,14,8)};button.Click+=(_,_)=>{result=app;dialog.DialogResult=true;};row.Children.Add(button);}panel.Children.Add(row);AppTheme.Attach(dialog,this);dialog.Content=panel;dialog.ShowDialog();return result;}
    private async void Discover_Click(object sender,RoutedEventArgs e){try{var candidates=await Task.Run(()=>Discovery.Existing(CatalogStore.Read()));var dialog=new Window{Owner=this,Title="Find existing desktop profiles",Width=740,Height=520,WindowStartupLocation=WindowStartupLocation.CenterOwner};var panel=new DockPanel{Margin=new Thickness(24)};var hint=new TextBlock{Text="Folders are candidates, not verified accounts. Import creates new Hatrack shortcuts; it does not copy login secrets or overwrite existing shortcuts.",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,18)};DockPanel.SetDock(hint,Dock.Top);panel.Children.Add(hint);var row=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,16,0,0)};DockPanel.SetDock(row,Dock.Bottom);var add=new Button{Content="Choose profile folder",Padding=new Thickness(14,8,14,8)};var import=new Button{Content="Import selected",Padding=new Thickness(14,8,14,8),Margin=new Thickness(12,0,0,0)};row.Children.Add(add);row.Children.Add(import);panel.Children.Add(row);var list=new ListBox{ItemsSource=candidates.Select(c=>c.Name+" · "+c.App+"\n"+c.DataPath+"\n"+c.Evidence)};panel.Children.Add(list);AppTheme.Attach(dialog,this);dialog.Content=panel;
        import.Click+=async(_,_)=>{if(list.SelectedIndex<0)return;var c=candidates[list.SelectedIndex];if(c.Name=="Original Codex"){System.Windows.MessageBox.Show(dialog,"The default Codex home belongs to your original desktop session. Create a fresh profile instead; adopting it could change the original login.","Keep original session separate");return;}var editor=new EditorWindow(installations,null,c){Owner=dialog};if(editor.ShowDialog()==true){dialog.Close();await Refresh();}};
        add.Click+=async(_,_)=>{var app=ChooseApp();if(app==null)return;var picker=new Microsoft.Win32.OpenFolderDialog{Title="Choose the existing profile data folder"};if(picker.ShowDialog(dialog)!=true)return;try{Paths.ValidateProfileFolder(picker.FolderName);if(app==DesktopApp.Codex&&Paths.Same(picker.FolderName,Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),".codex")))throw new ArgumentException("Keep the original Codex home separate. Choose another existing home or create a fresh profile.");var editor=new EditorWindow(installations,null,new(app.Value,Path.GetFileName(picker.FolderName),picker.FolderName,"","Selected folder")){Owner=dialog};if(editor.ShowDialog()==true){dialog.Close();await Refresh();}}catch(Exception ex){Error(ex);}};
        dialog.ShowDialog();
    }catch(Exception ex){Error(ex);}}
    private void Diagnostics_Click(object sender,RoutedEventArgs e){var lines=new List<string>{$"Hatrack {Program.Version} preview · Windows desktop only",Environment.OSVersion.ToString(),"No credentials, account IDs, conversations, or tokens are included.",""};lines.AddRange(installations.Select(i=>$"{i.App}: version {i.Version}; detected via {i.Source}"));lines.Add($"Managed profiles: {catalog.Profiles.Count}");lines.Add("Authentication and desktop-isolation release checks: pending manual verification.");var save=new SaveFileDialog{FileName="Hatrack-diagnostics.txt",Filter="Text (*.txt)|*.txt"};if(save.ShowDialog(this)==true)try{File.WriteAllLines(save.FileName,lines);Status.Text="Saved diagnostics without profile paths or credentials.";}catch(Exception ex){Error(ex);}}
    private void Theme_Changed(object sender,SelectionChangedEventArgs e){if(!ready)return;var theme=((ComboBoxItem)Theme.SelectedItem).Content.ToString()!;ApplyTheme(theme);try{CatalogStore.Update(c=>{c.Theme=theme;return true;});}catch(Exception ex){Error(ex);}}
    private void ApplyTheme(string theme)=>AppTheme.Apply(this,theme);
    internal void Error(Exception e){Status.Text=e.Message;System.Windows.MessageBox.Show(this,e.Message,"Hatrack",MessageBoxButton.OK,MessageBoxImage.Warning);}
}
